# Generated by Django 5.2.5 on 2025-09-02 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduation Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_unitec_email',
            field=models.BooleanField(default=False, verbose_name='Is Unitec Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='unitec_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unitec Student ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year Group'),
        ),
    ]
